const fs = require('fs');
const path = require('path');

// A simple blue shield icon (base64 of a valid 128x128 PNG)
// This is a minimal valid PNG to ensure no generation errors.
const base64Icon = 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAAXNSR0IArs4c6QAAArVJREFUeF7t0wENgAAUxLFlVzZ20IAmWE0D4Z+b3cwnL8/zPAePAqNAWwCgbf5jFwBgCKgCAFT5jxtAGFAFQKDyHzeAMKAKAEDlP24AYUAVAIDKf9wAwoAqAACV/7gBhAFVAAAq/3EDCAOqAABU/uMGBAAAqgAAVP7jBhAGVAEAqPzHDSAMqAIAUPmPG0AYUAUAoPIfN4AwoAoAQOU/bgBhQBUAgMp/3ADCgCoAAJX/uAGEAVUAACr/cQMIA6oAAFT+4wYQBlQBAKj8xw0gDKgCAFD5jxtAGFAFQKDyHzeAMKAKAEDlP24AYUAVAIDKf9wAwoAqAACV/7gBhAFVAAAq/3EDCAOqAABU/uMGEAzuAABU/uMGEmBAFQAAmf+4AYQBVQAAKv9xAwgDqgAAVP7jBhAGVAEAqPzHDSAMqAIAUPmPG0AYUAUAoPIfN4AwoAoAQOU/bgBhQBUAgMp/3ADCgCoAAJX/uAGEAVUAACr/cQMIA6oAAFT+4wYQBlQBAKj8xw0gDKgCAFD5jxtAGFAFQKDyHzeAMKAKAEDlP24AYUAVAIDKf9wAwoAqAACV/7gBhAFVAAAq/3EDCAOqAABU/uMGEAzuAABU/uMGEmBAFQAAmf+4AYQBVQAAKv9xAwgDqgAAVP7jBhAGVAEAqPzHDSAMqAIAUPmPG0AYUAUAoPIfN4AwoAoAQOU/bgBhQBUAgMp/3ADCgCoAAJX/uAGEAVUAACr/cQMIA6oAAFT+4wYQBlQBAKj8xw0gDKgCAFD5jxtAGFAFQKDyHzeAMKAKAEDlP24AYUAVAIDKf9wAwoAqAACV/7gBhAFVAAAq/3EDCAOqAABU/uMGEAb+uQEAvN7neR7e/gDeu0F5+qK0rAAAAABJRU5ErkJggg==';

const buffer = Buffer.from(base64Icon, 'base64');
const targetPath = path.join(__dirname, '../icons/shield_v129.png');

fs.writeFileSync(targetPath, buffer);
console.log('Created valid PNG icon:', targetPath);
